services:
  db:
    image: postgres:15
    container_name: db-dragons
    environment:
      - POSTGRES_DB=study
      - POSTGRES_USER=study
      - POSTGRES_PASSWORD=study
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - is-backend
  dragons:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: docker.io/dllnnx/is:dragons
    container_name: dragons
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - "8080:8080"
    networks:
      - is-backend
      - is-frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: is-frontend
    image: docker.io/dllnnx/is:frontend
    ports:
      - "80:80"
    networks:
      - is-frontend

volumes:
  pg_data:

networks:
  is-backend:
    name: is-backend
  is-frontend:
    name: is-frontend
